import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "@/app/components/maid/navigation";
import Dashboard from "../components/maid/leftside/dashboardMaid";
import Maid from "../components/maid";
 const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <>
      <Maid/>
      </>
      {children}
    </body>
  </html>
  );
}
