import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "@/app/components/Dashboard/navigation";
import DropdownBox from "../components/Dashboard/content/dropdown";
import Content from "../components/Dashboard/content";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <div style={{ display: 'flex', flexDirection: 'column', gap: '50px' }}>
      <Navigation/>
      <Content/>
      </div>
      {children}
    </body>
  </html>
  );
}
