import { Inter } from 'next/font/google';
import './globals.css';
import ClientProvider from '@/providers/client-provider';
import { MapProvider } from '@/providers/map-providers';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'merMaid',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, }:{children: React.ReactNode;}) {
  return (
    <html>
      <body className={inter.className}>
        <ClientProvider>
          <MapProvider>
            {children}
          </MapProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
