import { Inter } from 'next/font/google';
import './globals.css';
import ClientProvider from '@/providers/client-provider';
import { MapProvider } from '@/providers/map-providers';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, }:{children: React.ReactNode;}) {
  return (
      <div className={inter.className}>
        <ClientProvider>
          <MapProvider>
            {children}
          </MapProvider>
        </ClientProvider>
      </div>
  );
}
